// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfS1uwanMP5o7F4lpSIelONdJN8tjCEGc',
    appId: '1:705366481313:web:3f10a599879e25682ad3e0',
    messagingSenderId: '705366481313',
    projectId: 'college-connect-240c2',
    authDomain: 'college-connect-240c2.firebaseapp.com',
    storageBucket: 'college-connect-240c2.appspot.com',
    measurementId: 'G-1FX8EH6SDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeaG0zf-rynlrq86kKD4MlnVOhRs7QwE',
    appId: '1:705366481313:android:eaed5541f3e62c922ad3e0',
    messagingSenderId: '705366481313',
    projectId: 'college-connect-240c2',
    storageBucket: 'college-connect-240c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKI11Hs6Nm-pixDZKF8dM_K9hE9T6IMBE',
    appId: '1:705366481313:ios:c8f9569127f69dd52ad3e0',
    messagingSenderId: '705366481313',
    projectId: 'college-connect-240c2',
    storageBucket: 'college-connect-240c2.appspot.com',
    iosBundleId: 'com.example.rConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKI11Hs6Nm-pixDZKF8dM_K9hE9T6IMBE',
    appId: '1:705366481313:ios:21ed6306a0d183782ad3e0',
    messagingSenderId: '705366481313',
    projectId: 'college-connect-240c2',
    storageBucket: 'college-connect-240c2.appspot.com',
    iosBundleId: 'com.example.rConnect.RunnerTests',
  );
}
